import subprocess
import tempfile
from pathlib import Path

import kicad_sch_api as ksa

from app.schemas.harness_design import DesignData


class KiCadEngineService:
    """
    A service to interact with KiCad CLI and kicad-sch-api.
    """

    def __init__(self, cli_path: str):
        """
        Initializes the KiCadEngineService.

        Args:
            cli_path: The full path to the kicad-cli executable.
        """
        self.cli_path = cli_path

    def generate_sch_from_json(self, design_data: DesignData) -> str:
        """
        Generates a KiCad schematic file from JSON design data.

        Args:
            design_data: The Pydantic model of the design data.

        Returns:
            The file path of the generated .kicad_sch file.
        """
        sch = ksa.Schematic()
        for node in design_data.nodes:
            if node.type == 'connector':
                # Using a simple component for demonstration in Cycle 1
                sch.components.add(
                    lib="Connector:Conn_01x02",
                    ref=f"U{node.id}",
                    unit=1,
                    value="Conn"
                )

        with tempfile.NamedTemporaryFile(
            delete=False, suffix=".kicad_sch", mode='w'
        ) as temp_file:
            sch.save(temp_file.name)
            return temp_file.name

    def export_dxf(self, sch_file_path: str) -> str:
        """
        Exports a DXF file from a KiCad schematic file.

        Args:
            sch_file_path: The path to the .kicad_sch file.

        Returns:
            The file path of the generated .dxf file.
        """
        with tempfile.NamedTemporaryFile(
            delete=False, suffix=".dxf"
        ) as temp_dxf_file:
            temp_dxf_path = temp_dxf_file.name

        cmd = [
            self.cli_path, "sch", "export", "dxf",
            "--output", temp_dxf_path, sch_file_path
        ]
        subprocess.run(cmd, check=True, capture_output=True)
        return temp_dxf_path

    def export_bom(self, sch_file_path: str) -> str:
        """
        Exports a BOM file from a KiCad schematic file.

        Args:
            sch_file_path: The path to the .kicad_sch file.

        Returns:
            The file path of the generated BOM file (e.g., .csv).
        """
        output_dir = Path(tempfile.gettempdir())

        # kicad-cli for bom export creates a file with a fixed name in the output dir
        # Let's create a temporary directory to be sure about the output path
        with tempfile.TemporaryDirectory() as temp_dir:
            temp_bom_path_base = Path(temp_dir) / Path(sch_file_path).stem
            cmd = [
                self.cli_path, "sch", "export", "bom",
                "--output-dir", str(temp_dir), sch_file_path
            ]
            subprocess.run(cmd, check=True, capture_output=True)

            # The output file name is based on the input sch file name
            generated_bom_files = list(Path(temp_dir).glob("*.csv"))
            if not generated_bom_files:
                raise FileNotFoundError("BOM file was not generated by kicad-cli.")

            # Move the generated file to a persistent temporary location
            with tempfile.NamedTemporaryFile(
                delete=False, suffix=".csv"
            ) as final_bom_file:
                Path(generated_bom_files[0]).rename(final_bom_file.name)
                return final_bom_file.name
