"""Initial migration

Revision ID: b6d3963f98ef
Revises: None
Create Date: 2025-11-16 00:21:04.555116

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b6d3963f98ef"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "harnesses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_harnesses_name"), "harnesses", ["name"], unique=False)
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_id"), "projects", ["id"], unique=False)
    op.create_index(op.f("ix_projects_name"), "projects", ["name"], unique=True)
    op.create_table(
        "connectors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("logical_id", sa.String(), nullable=False),
        sa.Column("manufacturer", sa.String(), nullable=False),
        sa.Column("part_number", sa.String(), nullable=False),
        sa.Column("harness_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["harness_id"],
            ["harnesses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_connectors_logical_id"), "connectors", ["logical_id"], unique=False
    )
    op.create_table(
        "harness_designs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("design_data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_harness_designs_id"), "harness_designs", ["id"], unique=False
    )
    op.create_table(
        "wires",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("logical_id", sa.String(), nullable=False),
        sa.Column("manufacturer", sa.String(), nullable=False),
        sa.Column("part_number", sa.String(), nullable=False),
        sa.Column("color", sa.String(), nullable=False),
        sa.Column("gauge", sa.Float(), nullable=False),
        sa.Column("length", sa.Float(), nullable=False),
        sa.Column("harness_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["harness_id"],
            ["harnesses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_wires_logical_id"), "wires", ["logical_id"], unique=False)
    op.create_table(
        "pins",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("logical_id", sa.String(), nullable=False),
        sa.Column("connector_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["connector_id"],
            ["connectors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "connections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("harness_id", sa.UUID(), nullable=False),
        sa.Column("wire_id", sa.UUID(), nullable=False),
        sa.Column("from_pin_id", sa.UUID(), nullable=False),
        sa.Column("to_pin_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_pin_id"],
            ["pins.id"],
        ),
        sa.ForeignKeyConstraint(
            ["harness_id"],
            ["harnesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_pin_id"],
            ["pins.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wire_id"],
            ["wires.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("connections")
    op.drop_table("pins")
    op.drop_index(op.f("ix_wires_logical_id"), table_name="wires")
    op.drop_table("wires")
    op.drop_index(op.f("ix_harness_designs_id"), table_name="harness_designs")
    op.drop_table("harness_designs")
    op.drop_index(op.f("ix_connectors_logical_id"), table_name="connectors")
    op.drop_table("connectors")
    op.drop_index(op.f("ix_projects_name"), table_name="projects")
    op.drop_index(op.f("ix_projects_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_harnesses_name"), table_name="harnesses")
    op.drop_table("harnesses")
    # ### end Alembic commands ###
