"""Add assembly instruction fields to models

Revision ID: c1d0890e9fff
Revises: f03a520cf21f
Create Date: 2025-11-16 22:56:21.745645

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c1d0890e9fff"
down_revision = "f03a520cf21f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("connections", sa.Column("strip_length_a", sa.Float(), nullable=True))
    op.add_column("connections", sa.Column("strip_length_b", sa.Float(), nullable=True))
    op.add_column(
        "connections", sa.Column("terminal_part_number_a", sa.String(), nullable=True)
    )
    op.add_column(
        "connections", sa.Column("terminal_part_number_b", sa.String(), nullable=True)
    )
    op.add_column(
        "connections", sa.Column("marking_text_a", sa.String(), nullable=True)
    )
    op.add_column(
        "connections", sa.Column("marking_text_b", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("connections", "marking_text_b")
    op.drop_column("connections", "marking_text_a")
    op.drop_column("connections", "terminal_part_number_b")
    op.drop_column("connections", "terminal_part_number_a")
    op.drop_column("connections", "strip_length_b")
    op.drop_column("connections", "strip_length_a")
    # ### end Alembic commands ###
